#
# (C) Copyright 2014
# Bin Meng, bmeng.cn@gmail.com.
#
# Copyright (c) 2011 The Chromium OS Authors.
#
# (C) Copyright 2008
# Graeme Russ, graeme.russ@gmail.com.
#
# (C) Copyright 2006
# Wolfgang Denk, DENX Software Engineering, wd@denx.de.
#
# (C) Copyright 2002
# Daniel Engström, Omicron Ceti AB, daniel@omicron.se.
#
# SPDX-License-Identifier:	GPL-2.0+
#

obj-$(CONFIG_SYS_QUEENSBAY) += tnc_car.o
obj-$(CONFIG_SYS_QUEENSBAY) += tnc_dram.o
obj-$(CONFIG_SYS_QUEENSBAY) += tnc.o
